language: r
cache: packages
os: linux

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
    - libudunits2-dev
    - libv8-dev
    - libprotobuf-dev
    - libprotoc-dev
    - libproj-dev
    - libgeos-dev
    - libgdal-dev
    - protobuf-compiler
    - valgrind
    - libpq-dev
    - netcdf-bin

r_github_packages:
  - jimhester/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

jobs:
  include:
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel

env:
  global:
  - R_BUILD_ARGS="--no-build-vignettes --no-manual"
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
  - BOOTSTRAP_LATEX=""
